name: Build Documentation

on:
  pull_request:
    branches: [main]
  push: # Also build on push to main, for deployments or latest docs
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies and project in editable mode # More descriptive name
        run: |
          python -m pip install --upgrade pip
          
          pip install -r docs/requirements.txt
          
          pip install -e .

      - name: Generate API documentation stubs # Separated this step for clarity
        run: |
          cd docs 
          sphinx-apidoc -o . ../src/scisbi --force --implicit-namespaces --module-first
    

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
          
