name: Build Documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Check dependencies
        run: |
          cd docs
          make check-deps

      - name: Clean previous builds
        run: |
          cd docs
          make clean

      - name: Build documentation
        run: |
          cd docs
          make html

      - name: Verify build
        run: |
          cd docs
          if [ -d "_build/html" ] && [ -f "_build/html/index.html" ]; then
            echo "✓ Documentation built successfully"
            ls -la _build/html/
          else
            echo "✗ Documentation build failed"
            exit 1
          fi

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: documentation
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
