name: Build Documentation

on:
  pull_request:
    branches: [main]
  push: # Also build on push to main, for deployments or latest docs
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Generate API documentation stubs
        run: |
          cd docs
          # -o .: Output to the current docs directory
          # ../your_package_name: Path to your Python package relative to 'docs/'
          # --force: Overwrite existing RST files (important for updates)
          # --implicit-namespaces: Use if your package is a PEP 420 namespace package
          # --module-first: Puts module docs before package docs
          sphinx-apidoc -o . ../src/scicbi --force --implicit-namespaces --module-first

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
