name: Build Documentation

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docs:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          pip install -e .
        shell: pwsh

      - name: Check dependencies
        run: |
          cd docs
          make check-deps
        shell: pwsh

      - name: Clean previous builds
        run: |
          cd docs
          make clean
        shell: pwsh

      - name: Build documentation
        run: |
          cd docs
          make html
        shell: pwsh

      - name: Verify build
        run: |
          cd docs
          if (Test-Path "_build/html" -PathType Container -and (Test-Path "_build/html/index.html")) {
            Write-Host "✓ Documentation built successfully"
            Get-ChildItem _build/html/ | Format-List
          } else {
            Write-Host "✗ Documentation build failed"
            exit 1
          }
        shell: pwsh

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: documentation
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
