name: Build Documentation

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies and project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Clean previous builds
        run: |
          cd docs
          echo "Current directory: $(pwd)"
          echo "Available files:"
          ls -la
          echo "Running make clean..."
          make clean
          echo "Clean completed successfully"

      - name: Check build environment
        run: |
          cd docs
          echo "Checking dependencies and environment..."
          make check-deps
          echo "Environment check completed"

      - name: Build Sphinx documentation
        run: |
          cd docs
          echo "Building documentation with enhanced error reporting..."
          make html
          echo "Build completed successfully"

      - name: Debug build (on failure)
        if: failure()
        run: |
          cd docs
          echo "=== DEBUGGING FAILED BUILD ==="
          echo "Running debug build with maximum verbosity..."
          make debug || true
          echo ""
          echo "=== PACKAGE STRUCTURE ==="
          find ../src/scisbi -name "*.py" | head -20
          echo ""
          echo "=== SPHINX CONFIGURATION ==="
          cat conf.py | grep -E "(extensions|sys\.path)" || true
          echo ""
          echo "=== AVAILABLE TARGETS ==="
          make help

      - name: Verify build output
        run: |
          cd docs
          echo "Verifying build output..."
          if [ -d "_build/html" ]; then
            echo "✓ HTML build directory exists"
            echo "Build contents:"
            ls -la _build/html/
            if [ -f "_build/html/index.html" ]; then
              echo "✓ Index file created successfully"
            else
              echo "✗ Index file missing"
              exit 1
            fi
          else
            echo "✗ HTML build directory missing"
            exit 1
          fi

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: documentation
          path: docs/_build/html/

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
